export const DEFAULTS = {
  deeplApiBaseUrl: "https://api.deepl.com",
  defaultSourceLanguage: "EN",
  defaultTargetLanguage: "RU",
  logLevel: "info",
  maxConcurrentJobs: 2,
  maxRetryAttempts: 6,
  jobLeaseSeconds: 300,
  retryBaseSeconds: 60,
  publishOriginalOnExhaustedTransientFailure: true,
  healthServerEnabled: true,
  metricsEnabled: false,
  sourceDuplicateWindowSeconds: 900,
  attachmentMirrorMaxBytes: 20_000_000,
  port: 8080,
  railwayRunUid: 0,
  railwayHealthcheckTimeoutSec: 60,
  railwayDeploymentDrainingSeconds: 20,
  railwayDeploymentOverlapSeconds: 0,
  mockDeepl: false,
  skipStartupDependencyChecks: false,
  requirePersistentVolume: false,
} as const;
